version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  go-app:
    image: wasm-handler
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - WS_PORT=3001
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_KEY_LIFETIME=1h
    ports:
      - 3001:3001
    depends_on:
      - redis
